language: python
sudo: false
python:
  - "3.5"
install:
  - travis_retry pip install tox
script:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then travis_retry tox -e py35; fi
  - travis_retry tox -e flake
